# Generated by Django 4.2.18 on 2026-09-22 05:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swarm', '0018_conversationsummary_include_in_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatattachment',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='herdragent',
            name='remote',
            field=models.CharField(blank=True, default='', help_text='Empty = localhost (no --remote). Examples: you@198.51.100.36, workbox, ssh://you@server:2222.', max_length=255),
        ),
    ]
