"""Support Agent assistant helper for scaffolding custom BaseCliAgent drivers.

REQ-889: Enables the Support Agent (wusupport) to help users integrate new
or proprietary agentic CLIs by generating, verifying, and registering
a protocol-compliant BaseCliAgent subclass.
"""
from __future__ import annotations

import logging
import os
import re
from typing import Any

from swarm.core.cli_driver import test_cli_binary
from swarm.core.cli_registry import get_cli_registry

logger = logging.getLogger(__name__)

SAFE_IDENTIFIER_RE = re.compile(r"^[a-z][a-z0-9_]{1,30}$")


def scaffold_cli_agent_driver(
    name: str,
    display_name: str,
    default_binary: str,
    exec_args: list[str] | None = None,
    output_parse_mode: str = "text",
    json_path: str = "",
    resume_args: list[str] | None = None,
    env_allowlist: list[str] | None = None,
    destination_dir: str | None = None,
    verify_probe: bool = True,
) -> dict[str, Any]:
    """Generate, test, and register a new BaseCliAgent subclass for a custom CLI.

    Called by the Support Agent when walking the user through adding a new CLI.
    """
    clean_name = name.strip().lower()
    if not SAFE_IDENTIFIER_RE.match(clean_name):
        return {
            "ok": False,
            "error": f"Invalid CLI name '{clean_name}'. Must start with a letter and contain only lowercase letters, digits, or underscores (2-31 chars).",
        }

    clean_display = display_name.strip() or clean_name.capitalize()
    clean_binary = default_binary.strip() or clean_name

    if verify_probe:
        probe = test_cli_binary(clean_binary)
        if not probe.get("ok"):
            logger.warning("Scaffold probe check warning for %s: %s", clean_binary, probe.get("message"))

    if destination_dir is None:
        destination_dir = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "custom_cli_agents",
        )

    os.makedirs(destination_dir, exist_ok=True)
    init_path = os.path.join(destination_dir, "__init__.py")
    if not os.path.exists(init_path):
        with open(init_path, "w", encoding="utf-8") as f:
            f.write('"""Custom agentic CLI drivers registered by Support Agent."""\n')

    file_path = os.path.join(destination_dir, f"{clean_name}.py")

    class_name = f"{''.join(word.capitalize() for word in clean_name.split('_'))}CliAgent"
    exec_flags = exec_args if exec_args is not None else ["-p", "{prompt}"]
    resume_flags = resume_args if resume_args is not None else []
    allowlist = env_allowlist or []

    # Build template code
    code_lines = [
        '"""Custom driver for ' + clean_display + ' generated by Support Agent."""',
        "from __future__ import annotations",
        "",
        "import json",
        "from typing import Any",
        "from swarm.core.cli_driver import BaseCliAgent, split_cli_string",
        "",
        "",
        f"class {class_name}(BaseCliAgent):",
        f'    name = "{clean_name}"',
        f'    display_name = "{clean_display}"',
        f'    default_binary = "{clean_binary}"',
        f"    env_allowlist = {repr(allowlist) if allowlist else 'None'}",
        f'    list_capability = "{"works" if resume_flags else "unsupported"}"',
        "",
        "    def build_exec_argv(",
        "        self,",
        "        prompt: str,",
        "        session_id: str | None = None,",
        "        model: str | None = None,",
        "        binary_override: str | None = None,",
        "    ) -> list[str]:",
        "        bin_cmd = split_cli_string(binary_override or self.default_binary)",
        f"        template = {repr(exec_flags)}",
        "        substituted = [flag.replace('{prompt}', prompt) for flag in template]",
        "        argv = [*bin_cmd, *substituted]",
        "        if session_id and self.resume_session_argv(session_id):",
        "            argv = [*argv[:1], *self.resume_session_argv(session_id), *argv[1:]]",
        "        if model:",
        "            argv.extend(['--model', model])",
        "        return argv",
        "",
        "    def parse_output(self, stdout: str) -> str:",
    ]

    if output_parse_mode == "json" and json_path:
        code_lines.extend([
            "        try:",
            "            data = json.loads(stdout)",
            "            if isinstance(data, dict):",
            f'                return str(data.get("{json_path}") or stdout).strip()',
            "        except Exception:",
            "            pass",
            "        return stdout.strip()",
        ])
    else:
        code_lines.append("        return stdout.strip()")

    code_lines.extend([
        "",
        "    def resume_session_argv(self, session_id: str) -> list[str]:",
        f"        template = {repr(resume_flags)}",
        "        return [flag.replace('{session_id}', session_id) for flag in template]",
        "",
    ])

    code_content = "\n".join(code_lines) + "\n"

    try:
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code_content)
    except OSError as exc:
        return {"ok": False, "error": f"Failed to write driver file: {exc}"}

    # Reload into registry
    registry = get_cli_registry()
    loaded_count = registry.load_custom_drivers(destination_dir)

    return {
        "ok": True,
        "name": clean_name,
        "class_name": class_name,
        "file_path": file_path,
        "registered": bool(registry.get(clean_name)),
        "loaded_count": loaded_count,
    }
