"""#857 — generate the browsable SDK reference pages.

Writes ``docs/sdk/reference/*.md`` mkdocstrings directives for the modules
in :data:`REGISTRY`, plus an ``index.md`` overview. Idempotent: rerun after
adding modules to the registry and rebuild mkdocs. Run hermetically:

    API_AUTH_TOKEN="" .venv/bin/python scripts/gen_sdk_reference.py
"""

from __future__ import annotations

from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "docs" / "sdk" / "reference"

# section title -> list of dotted module paths rendered on that page.
REGISTRY: dict[str, list[str]] = {
    "sandbox": [
        "swarm.core.sandbox.base",
        "swarm.core.sandbox.manager",
        "swarm.core.sandbox.opt_in",
        "swarm.core.sandbox.display",
    ],
    "roles": [
        "swarm.core.roles.base",
    ],
    "remotes": [
        "swarm.remotes.base",
        "swarm.remotes.registry",
    ],
    "herdr_ssh": [
        "swarm.herdr.ssh",
    ],
}

HEADER = """<!-- Generated by scripts/gen_sdk_reference.py — do not edit by hand. -->

"""


def write_page(section: str, modules: list[str]) -> Path:
    lines = [HEADER, f"# {section.replace('_', ' ').title()} reference", ""]
    for module in modules:
        lines += ["## `:::" + module + "`", "", f"::: {module}", ""]
    path = OUT / f"{section}.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    return path


def write_index() -> Path:
    entries = "\n".join(
        f"- [{name.replace('_', ' ').title()}]({name}.md)" for name in sorted(REGISTRY)
    )
    text = (
        HEADER
        + "# Open Swarm SDK reference\n\n"
        + "Browsable API reference for the Blueprint SDK surfaces, generated\n"
        + "from the modules in `scripts/gen_sdk_reference.py` (REQ-857 / #857).\n"
        + "Pages render `swarm.core` SDK surfaces (sandbox, roles) plus the\n"
        + "remote-adapter and Herdr SSH layers. The worked half of the SDK\n"
        + "lives in `docs/sdk/BLUEPRINT_SDK.md` and the `example_*` blueprints.\n\n"
        + "## Sections\n\n"
        + entries
        + "\n"
    )
    path = OUT / "index.md"
    path.write_text(text, encoding="utf-8")
    return path


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for section, modules in REGISTRY.items():
        print("wrote", write_page(section, modules).relative_to(REPO))
    print("wrote", write_index().relative_to(REPO))


if __name__ == "__main__":
    main()
